
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Omar", email = "sunn@atumm.org"},
]
dependencies = [
    "langchain>=0.0.189",
    "huggingface-hub>=0.15.1",
    "typer>=0.9.0",
    "python-decouple>=3.8",
]
requires-python = ">=3.11"
license = {text = "MIT"}
